In [1]:
import sys
import os
# Adding the root to the path to use utils folder
sys.path.append(os.path.abspath(os.path.join('..')))

from utils.db_utils import run_query 
from utils.custom_plots import distribution_plot

<div class="alert alert-block alert-success">


### In this notebook we are going to have a first look at the tables of this database

**1-what is their purpose and what are they features(columns)?**

**2-what is their relation and how they are connected?**

**3-how many null or missing values they have?**

**4-what is their distribution? are they normal?**

**5-how their outliers are layedout?**

**6-what are the cleaning opportunities?**

<div class="alert alert-block alert-success">

# Table: Competition

In [2]:
competitions_summary = run_query('select * from competitions')

competitions_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)

  competition_id                           name             type country_name
0            CIT                      italy-cup     domestic_cup        Italy
1           NLSC           johan-cruijff-schaal            other  Netherlands
2            GRP                kypello-elladas     domestic_cup       Greece
3           POSU  supertaca-candido-de-oliveira            other     Portugal
4           RUSS              russian-super-cup            other       Russia
5            SUC                      supercopa            other        Spain
6            DK1                    superligaen  domestic_league      Denmark
7            ES1                         laliga  domestic_league        Spain
8            FR1                        ligue-1  domestic_league       France
9            IT1                        serie-a  domestic_league        Italy

In [3]:
competitions_summary.describe()

       competition_id       name             type country_name
count              43         43               43           36
unique             43         43                4           14
top               CIT  italy-cup  domestic_league      England
freq                1          1               14            4

In [4]:
competitions_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   competition_id  43 non-null     str
 1   name            43 non-null     str
 2   type            43 non-null     str
 3   country_name    36 non-null     str
dtypes: str(4)
memory usage: 1.5 KB

In [7]:
competitions_dist = distribution_plot(competitions_summary, n_cols=4, title='Competitions Distribution')
competitions_dist

<div class="alert alert-block alert-success">

## Competitions summary: 
**this table stores data of each football competition**

### columns:
**competition_id:** unique string id of the competition

**name:** full name of the competition

**type:** type of the competition , we have only 4 types(domestic, international , ...)

**country_name:** name of the country where competition belongs to.(it has 7 null values for competitions that are international)